cLock: Avoid possible NPE when releasing wakelock
E AndroidRuntime: FATAL EXCEPTION: main
E AndroidRuntime: Process: com.cyanogenmod.lockclock, PID: 2838
E AndroidRuntime: java.lang.RuntimeException: Unable to stop service
com.cyanogenmod.lockclock.weather.WeatherUpdateService@c53a204:
java.lang.NullPointerException: Attempt to invoke virtual method
'void android.os.PowerManager$WakeLock.release()' on a null object reference
E AndroidRuntime: 	at android.app.ActivityThread.handleStopService(ActivityThread.java:3398)
E AndroidRuntime: 	at android.app.ActivityThread.-wrap27(ActivityThread.java)
E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1606)
E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6186)
E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke
virtual method 'void android.os.PowerManager$WakeLock.release()' on a null object reference
E AndroidRuntime: 	at com.cyanogenmod.lockclock.weather.WeatherUpdateService$WorkerThread.
broadcastAndCleanUp(WeatherUpdateService.java:408)
E AndroidRuntime: 	at com.cyanogenmod.lockclock.weather.WeatherUpdateService$WorkerThread.
tearDown(WeatherUpdateService.java:319)
E AndroidRuntime: 	at com.cyanogenmod.lockclock.weather.WeatherUpdateService.
onDestroy(WeatherUpdateService.java:439)
E AndroidRuntime: 	at android.app.ActivityThread.handleStopService(ActivityThread.java:3381)

Change-Id: I13113b95c67b37ed32ac2606b79aebe2c82b7967