Update patch set 1
Patch Set 1:

David, this breaks build

packages/apps/LockClock/src/com/cyanogenmod/lockclock/ClockWidgetService.java:457: cannot find symbol
symbol  : variable weather_cannot_reach_provider
location: class com.cyanogenmod.lockclock.R.string
        String noData = getString(R.string.weather_cannot_reach_provider, getString(R.string.weather_source));
                                          ^
packages/apps/LockClock/src/com/cyanogenmod/lockclock/ClockWidgetService.java:480: setWeatherClickListener(android.widget.RemoteViews) in com.cyanogenmod.lockclock.ClockWidgetService cannot be applied to (android.widget.RemoteViews,boolean)
        setWeatherClickListener(weatherViews, true);
        ^
2 errors

Patch-set: 1
Reviewer: Taichi Nishimura <1579@1ec6b3db-b2c1-4fa4-84a2-4c7efe89ba71>
Label: Verified=0